# Generated by Django 4.2.3 on 2023-07-23 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Cpf',
            field=models.CharField(default='', max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='User',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
    ]
